import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import "@/styles/tailwind.css";
import "../styles/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kundan Kumar",  // Updated title
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",  // Favicon icon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
